# Generated by Django 5.0.1 on 2025-11-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="withdrawn_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        # Add database constraint to ensure withdrawn_amount is non-negative
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                check=models.Q(withdrawn_amount__gte=0),
                name="withdrawn_amount_non_negative",
            ),
        ),
        # Add database constraint to ensure withdrawn_amount doesn't exceed current_amount
        # Note: This is a soft constraint since we calculate net_amount differently
        # The actual validation happens in the application layer
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                check=models.Q(withdrawn_amount__lte=models.F("current_amount")),
                name="withdrawn_amount_lte_current_amount",
            ),
        ),
    ]
