# Generated by Django 5.0.1 on 2025-11-20 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("donor", "Donor Badge"),
                            ("creator", "Creator Badge"),
                            ("milestone", "Milestone Badge"),
                        ],
                        max_length=20,
                    ),
                ),
                ("icon_url", models.URLField(blank=True, null=True)),
                ("criteria_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("criteria_count", models.IntegerField(blank=True, null=True)),
                ("color", models.CharField(default="#000000", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
                "db_table": "badges",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_badges", to="badges.badge"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="badges", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "User Badge",
                "verbose_name_plural": "User Badges",
                "db_table": "user_badges",
                "ordering": ["-earned_at"],
                "unique_together": {("user", "badge")},
            },
        ),
    ]
