# Generated by Django 5.0.1 on 2025-11-20 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("donor_name", models.CharField(blank=True, max_length=255, null=True)),
                ("donor_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("platform_fee", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="BDT", max_length=3)),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("payment_method", models.CharField(max_length=50)),
                ("payment_reference", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="donations", to="campaigns.campaign"
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Donation",
                "verbose_name_plural": "Donations",
                "db_table": "donations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("donation", "Donation"), ("refund", "Refund"), ("withdrawal", "Withdrawal")],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="BDT", max_length=3)),
                ("payment_gateway", models.CharField(max_length=50)),
                ("gateway_transaction_id", models.CharField(blank=True, max_length=255, null=True)),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "donation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="donations.donation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentWebhook",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gateway", models.CharField(max_length=50)),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                ("headers", models.JSONField(default=dict)),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhooks",
                        to="donations.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Webhook",
                "verbose_name_plural": "Payment Webhooks",
                "db_table": "payment_webhooks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["campaign", "status"], name="donations_campaig_59c31d_idx"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["donor", "-created_at"], name="donations_donor_i_1842e7_idx"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["transaction_id"], name="donations_transac_5032b8_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["transaction_id"], name="transaction_transac_5011c8_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["gateway_transaction_id"], name="transaction_gateway_cb205b_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["status", "-created_at"], name="transaction_status_b84006_idx"),
        ),
    ]
